import  numpy as np
matrix=np.random.randint(10,size=(2,2))
print("random generated Matrix")
print(matrix)
det=np.linalg.det(matrix)
print("Determinant of matrix: ",det)
inverse=np.linalg.inv(matrix)
print("Inverse of matrix:\n",inverse)
rank=np.linalg.matrix_rank(matrix)
print("Rank of the matrix:",rank)
EVal,EVect = np.linalg.eig(matrix)
print("Eigen values:")
print(EVal)
print("Eigen vector")
print(EVect)
array_ID=matrix.flatten()
print("transform Matrix in1_d array:",array_ID)